language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n chemprop python=$TRAVIS_PYTHON_VERSION
  - conda activate chemprop
  - conda install -c conda-forge rdkit
  - conda install pytest
  - pip install git+https://github.com/bp-kelley/descriptastorus
  - pip install -e .
script:
  - pytest
