stages:
  train:
    cmd: python scripts/baseline_improvements/chemprop/train.py --config_path scripts/baseline_improvements/chemprop/datasets/config.json
      --data_path scripts/baseline_improvements/chemprop/datasets/logp_wo_averaging_train.csv
      --dataset_type regression
    deps:
    - scripts/baseline_improvements/chemprop/datasets
    - scripts/baseline_improvements/chemprop/train.py
    outs:
    - scripts/baseline_improvements/chemprop/out
