stages:
  train:
    cmd: /home/mol/anaconda3/envs/chemprop/bin/python3.8 ./scripts/baseline_improvements/chemprop/train.py
      --config_path ./scripts/baseline_improvements/chemprop/datasets/config.json
      --dataset_type regression --data_path ./data/raw/baselines/dmpnn/train_val_dataset.csv
    deps:
    - ./scripts/baseline_improvements/chemprop/datasets
    outs:
    - ./scripts/baseline_improvements/chemprop/out
