file_prefix: logd_Lip_wo_averaging_train_val_dataset
split_file_prefix: logd_Lip_wo_averaging
input_path: ./data/3_final_data/split_data
save_dir: ./data/raw/baselines/dmpnn/logs/exp_402
epochs: 1000
patience: 10
delta: 0.001
features_generator: [rdkit_wo_fragments_and_counts]
no_features_scaling: True
target_columns: [logD]
split_type: k-fold
num_folds: 4
data_path: ./data/raw/baselines/dmpnn/
additional_encoder: False
