file_prefix: logp_wo_logp_json_wo_averaging
split_file_prefix: logp_wo_logp_json_wo_averaging
input_path: ./data/3_final_data/split_data
save_dir: ./data/raw/baselines/dmpnn/logs/exp_430
epochs: 1000
patience: 10
delta: 0.001
features_generator: [rdkit_wo_fragments_and_counts]
no_features_scaling: True
target_columns: [logP]
split_type: k-fold
num_folds: 4
additional_encoder: False
gcn_encoder: True
hidden_size: 900
substructure_hidden_size: 0
depth: 6
ffn_num_layers: 3
data_path: ./data/3_final_data/split_data/
separate_test_path: ./data/3_final_data/split_data/