name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
          chmod +x Miniconda3-latest-Linux-x86_64.sh
          ./Miniconda3-latest-Linux-x86_64.sh -b
          ~/miniconda3/bin/conda  install -y -c conda-forge rdkit
          ~/miniconda3/bin/conda init
          
          ~/miniconda3/bin/pip install git+https://github.com/bp-kelley/descriptastorus
          ~/miniconda3/bin/pip install chemprop
          ~/miniconda3/bin/python train.py --data_path ../../../data/raw/baselines/dmpnn/logp_wo_averaging_train_val.cs
          v --dataset_type regression --save_dir ../../../data/raw/baselines/dmpnn/logs/exp_210 --separate_test_path ../../../data/raw/baselines/dmpnn/logp_wo_averaging_test.csv --epochs 100 --depth 6 --features_generator rdkit_2d_normalized_best --no_features_scaling --split_type 'k-fold' --num-folds 4

          cat quiet.log >> report.md
          cml-send-comment report.md
